# Course Name: **AI Mastery Bootcamp: AI Algorithms, DeepSeek AI, AI Agents**

# Section 16: **Basics of TensorFlow**

## Basics of TensorFlow

### Tensors and Operations
* Introduction to Tensors
* What are Tensors?
  * Scalar (Rank-0 Tensor)
  * Vector (Rank-I Tensor)
  * Matrix (Rank-2 Tensor)
  * Higher-Rank Tensors:
* Properties of Tensors
  * Shape
  * Data Type (dtype)
  * Values

In [1]:
import tensorflow as tf
# Create tensors
tensor_a= tf.constant([[1, 2], [3, 4]], dtype = tf.float64)
tensor_b= tf.constant([[5, 6], [7, 8]], dtype = tf.float64)

In [2]:
# Arithmetic Function

## Addition
result_add= tf.add(tensor_a, tensor_b)

## Subtraction
result_sub= tf.subtract(tensor_a, tensor_b)

## Multiplication
result_mul= tf.multiply(tensor_a, tensor_b)

## Division
result_div= tf.divide(tensor_a, tensor_b)

print("Addition \n", result_add)
print("Subtraction \n", result_sub)
print("Multiplication \n", result_mul)
print("Division \n", result_div)

Addition 
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float64)
Subtraction 
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float64)
Multiplication 
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float64)
Division 
 tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [3]:
# Mathematical Function

## Square
result_square= tf.square(tensor_a)

## Square root
result_sqrt= tf.math.sqrt(tensor_a)

## Exponential
result_exp= tf.exp(tensor_a)

## Logarithm
result_log= tf.math.log(tensor_a)

print("Square \n", result_square)
print("Square root \n", result_sqrt)
print("Exponential \n", result_exp)
print("Logarithm \n", result_log)

Square 
 tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float64)
Square root 
 tf.Tensor(
[[1.         1.41421356]
 [1.73205081 2.        ]], shape=(2, 2), dtype=float64)
Exponential 
 tf.Tensor(
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]], shape=(2, 2), dtype=float64)
Logarithm 
 tf.Tensor(
[[0.         0.69314718]
 [1.09861229 1.38629436]], shape=(2, 2), dtype=float64)


In [4]:
# Reduction Operations

## Sun along axis
result_sum= tf.reduce_sum(tensor_a, axis=1)

## Mean along axis
result_mean= tf.reduce_mean(tensor_a)

## Maximum Value
result_max= tf.reduce_max(tensor_a)

## Minimum Value
result_min= tf.reduce_min(tensor_a)

print("Sum  \n", result_sum)
print("Mean \n", result_mean)
print("Maximum Value \n", result_max)
print("Minimum Value \n", result_min)

Sum  
 tf.Tensor([3. 7.], shape=(2,), dtype=float64)
Mean 
 tf.Tensor(2.5, shape=(), dtype=float64)
Maximum Value 
 tf.Tensor(4.0, shape=(), dtype=float64)
Minimum Value 
 tf.Tensor(1.0, shape=(), dtype=float64)


In [5]:
# Matrix Operations

## Matrix Multiplication
matrix_matmul= tf.matmul(tensor_a, tensor_b)

## Transpose
matrix_transpose= tf.transpose(tensor_a)

## Matix Inverse (Requires Tensorflow Addons)
result_inverse= tf.linalg.inv(tensor_a)

## Reshape
matrix_reshape= tf.reshape(tensor_a, [4, 1])

print("Matrix Multiplication \n", matrix_matmul)
print("Transpose \n", matrix_transpose)
print("Inverse \n", result_inverse)
print("Reshape \n", matrix_reshape)

Matrix Multiplication 
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float64)
Transpose 
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float64)
Inverse 
 tf.Tensor(
[[-2.   1. ]
 [ 1.5 -0.5]], shape=(2, 2), dtype=float64)
Reshape 
 tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]], shape=(4, 1), dtype=float64)


In [6]:
# Indexing and Slicing

## Accessing Specific Elements
element= tensor_a[0, 0]

## Slicing
slice_tensor= tensor_a[:, 1]

## Boolean Indexing
filtered_tensor= tf.boolean_mask(tensor_a, tensor_a > 2)

print("Element \n", element)
print("Slice \n", slice_tensor)
print("Filtered Tensor \n", filtered_tensor)

Element 
 tf.Tensor(1.0, shape=(), dtype=float64)
Slice 
 tf.Tensor([2. 4.], shape=(2,), dtype=float64)
Filtered Tensor 
 tf.Tensor([3. 4.], shape=(2,), dtype=float64)


In [8]:
# Broadcasting

## Broadcasting in arithmetic operations
tensor_C= tf.constant([1, 2], dtype = tf.float64)
result_broadcast= tensor_a + tensor_C

print("Broadcasting \n", result_broadcast)

Broadcasting 
 tf.Tensor(
[[2. 4.]
 [4. 6.]], shape=(2, 2), dtype=float64)


In [9]:
# Constants
constant_tensor= tf.constant([1, 2, 3, 4, 5], dtype = tf.float64)
print("Constant Tensor \n", constant_tensor)

Constant Tensor 
 tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float64)


In [10]:
# Variables
initial_values= tf.random.normal(shape=(3, 3))
variable_tensor= tf.Variable(initial_values)
print("Intial Tensor Variable \n", variable_tensor)

# Update variable tensor
new_values= tf.random.normal(shape=(3, 3))
variable_tensor.assign(new_values)
print("Updated Tensor Variable \n", variable_tensor)

Intial Tensor Variable 
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.51709896, -1.2771713 , -0.75847626],
       [-1.488559  ,  0.63512135, -0.34967172],
       [ 0.49878877,  0.45374238, -1.3809302 ]], dtype=float32)>
Updated Tensor Variable 
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.6607301 ,  0.66573006, -1.0928854 ],
       [ 1.1083727 ,  0.20950831,  1.3411124 ],
       [ 0.2045033 , -1.8330133 , -0.60882187]], dtype=float32)>


In [ ]:
# Palceholder (Deprecated)

## Created a placeholder for input data (Deprecated)
x= tf.compat.v1.placeholder(tf.float32, shape=(None, 10))
print("Placeholder \n", x)

## Placeholder usage in computational graph
y= tf.square(x)
print("Placeholder \n", y)

In [12]:
# Tensorflow 2.x Approcah
x= tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

## Direct compute without placeholder
y= tf.square(x)
print("Without Placeholder \n", y)

Without Placeholder 
 tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)


## Graphs and Sessions

### TensorFlow Computational Graph
1. What is a Computational Graph?
  * Definition
  * Nodes
  * Edges
2. Building a Computational Graph
  * Define Operations
  * Create Tensors
  * Connect Operations

In [13]:
# Define operations
a= tf.constant([[1, 2], [3, 4]], dtype = tf.float64)
b= tf.constant([[5, 6], [7, 8]], dtype = tf.float64)
c= tf.matmul(a, b)

# Print the computational graph
print(tf.compat.v1.get_default_graph().as_graph_def())

versions {
  producer: 1994
}



3. Visualizing the Computational Graph?
  * TensorBoard
  * tf.summary.FileWriter

In [ ]:
with tf.compat.v1.Session() as sess:
  writer= tf.summary.FileWriter(logdir='logs', graph= sess.graph)
  writer.close()

4. Executing the Computational Graph

In [ ]:
with tf.compat.v1.Session() as sess:
  result= sess.run(c)
  print("Result: ", result)

5. Benefits of Computational Graphs
  1. Optimization
  2. Portability
  3. Debugging

In [21]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()  # Disable TensorFlow 2.x behavior to use 1.x features

# Step 1: Create a computational graph
a = tf.constant(5, name="a")  # Define constant 'a'
b = tf.constant(3, name="b")  # Define constant 'b'

# Define an operation (e.g., addition)
c = tf.add(a, b, name="c")  # c = a + b

# Step 2: Execute the graph in a session
with tf.Session() as sess:
    result = sess.run(c)  # Run the operation within the session
    print("The result of the computation is:", result)

Instructions for updating:
non-resource variables are not supported in the long term


The result of the computation is: 8


## Managing Graphs and Sessions
### TensorFlow Graphs
  * Definition
  * Default Graph
  * Multiple Graphs

In [22]:
import tensorflow as tf

# Crate a new tensorflow graph
graph= tf.Graph()

# Add operations to the graph
with graph.as_default():
  a= tf.constant(5)
  b= tf.constant(3)
  c= tf.add(a, b)

In [23]:
# Create a tensorflow session
with tf.compat.v1.Session(graph= graph) as sess:
  result= sess.run(c)
  print("Result: ", result)

Result:  8


## Basic Neural Networks with TensorFlow

In [ ]:
# 1. Import library
import tensorflow as tf

# 2. Define the Architecture
## Example architecture for a simple neural network
input_size= 784   # Number of input features (e.g. , pixels in an image)
hidden_size = 128 # Number of neurons in the hidden layer
output_size = 10  # Number of output classes (e.g., digits 0-9)

# 3. Specify the Input and Output Layers

X= tf.placeholder(tf.float32, shape=[None, input_size])
y= tf.placeholder(tf. float32, shape=[None, output_size])

# 4. Configure the Hidden Layers
## Hidden layer
hidden_layer = tf.layers.dense(inputs=X, units=hidden_size, activation=tf.nn.relu)

# 5. Specify the Output Layer ## Output layer
output_layer = tf.layers.dense(inputs=hidden_layer, units=output_size)

# 6. Define the Loss Function
## Cross-entropy loss for classification tasks
loss= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=output_layer))

# 7. Select the Optimization Algorithm
## Adam optimizer for gradient descent
optimizer = tf.train.AdamOptimizer(learning_rate= 0.001)
train_op = optimizer.minimize(loss)

# 8. Initialize Variables
init = tf.global_variables_initializer()
# Start TensorFlow session
with tf.Session() as sess:
  sess.run(init)

# 9. Train the Model

## Example training loop
for epoch in range(num_epoch):

  ### Perform forward and backword pass
  _, curr_loss= sess.run([train_op, loss],
                         feed_dict= {X: input_data, y: target_labels})

  ### print training loss
  print(f"Epoch {epoch+1}, Loss: {curr_loss:.4f}")

# 10. Evaluate the Model (Optional)

## Example evaluation

accuracy = sess.run(accuracy_op, feed_dict={X: test_data, y: test_labels})
print(f"Test Accuracy: {accuracy * 100:.2f}%")

## Activation Function

In [ ]:
# 1. Linear Activation Function
## f(x)= x
output= tf.keras.activations.linear(input)

# 2. Sigmoid Activation Function
output= tf.keras.activations.sigmoid(input)

# 3. Hyperbolic Tangent (Tanh) Activation Function
output= tf.keras.activations.tanh(input)

# 4. Rectified Linear Unit (ReLU) Activation Function
output= tf.keras.activations.relu(input)

# 5. Rectified Linear Unit (ReLU) Activation Function
output= tf.keras.activations.LeakyReLU(input)

# 6. Softmax Activation Function
output= tf.keras.activations.softmax(input)

## Loss Functions

In [ ]:
## MSE
tf.keras.losses.mean_squared_error()

## Binary Cross-Entropy
tf.keras.losses.binary_crossentropy()

## Categorical Cross-Entropy
tf.keras.losses.categorical_crossentropy()

## Sparse Categorical Cross-Entropy
tf.keras.losses.sparse_categorical_crossentropy()


## Optimizers

In [ ]:
## Stochastic Gradient Descent (SGD)
tf.keras.optimizers.SGD(learning_rate=0.01)

## Adam Optimizer
tf.keras.optimizers.Adam(learning_rate=0.01)

## RMSprop Optimizer
tf.keras.optimizers.RMSprop(learning_rate=0.01)

## Adagrad
tf.keras.optimizers.Adagrad(learning_rate=0.01)